# Generated by Django 4.1.4 on 2023-01-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='userRole',
            field=models.CharField(choices=[('manager', 'MANAGER'), ('customer', 'CUSTOMER')], default='customer', max_length=100),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='managerValidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='userRole',
            field=models.CharField(choices=[('manager', 'MANAGER'), ('customer', 'CUSTOMER')], default='customer', max_length=100),
        ),
    ]
