# Generated by Django 4.1.4 on 2023-01-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=100)),
                ('slug', models.SlugField(default='untitled')),
                ('date', models.DateField(default='1900')),
                ('thumb', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
    ]
