# Generated by Django 4.1.4 on 2023-01-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=100)),
                ('slug', models.SlugField(default='untitled')),
                ('date', models.DateField(default='1900')),
                ('description', models.TextField(default='To Be Filled')),
                ('posterImage', models.ImageField(default='default.png', upload_to='')),
                ('startTime', models.TimeField(default='00:00')),
                ('endTime', models.TimeField(default='00:00')),
                ('screeningRoom', models.IntegerField(choices=[(1, 'Room1'), (2, 'Room2')], default='0')),
                ('remainingSeats', models.IntegerField(default=0)),
            ],
        ),
    ]
