# Generated by Django 4.1.4 on 2023-01-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newshow',
            name='endtime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='newshow',
            name='screeningroom',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade')], default='0'),
        ),
        migrations.AddField(
            model_name='newshow',
            name='starttime',
            field=models.TimeField(default='00:00'),
        ),
    ]
