# Generated by Django 4.1.4 on 2023-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_newshow_endtime_newshow_screeningroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newshow',
            old_name='endtime',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='newshow',
            old_name='thumb',
            new_name='posterImage',
        ),
        migrations.RenameField(
            model_name='newshow',
            old_name='starttime',
            new_name='startTime',
        ),
        migrations.RemoveField(
            model_name='newshow',
            name='screeningroom',
        ),
        migrations.AddField(
            model_name='newshow',
            name='screeningRoom',
            field=models.IntegerField(choices=[(1, 'Room1'), (2, 'Room2')], default='0'),
        ),
    ]
