# Generated by Django 4.1.4 on 2023-01-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_reservation_alter_newshow_date_alter_newshow_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='startTime',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seatNumber',
            field=models.IntegerField(default=0),
        ),
    ]
