# Generated by Django 4.1.4 on 2023-01-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_newshow_remainingseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='newshow',
            name='description',
            field=models.TextField(default='To Be Filled'),
        ),
    ]
