# Generated by Django 4.1.4 on 2023-01-22 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_remove_newshow_date_remove_newshow_remainingseats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AlterField(
            model_name='newshow',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 6, 1, 98869)),
        ),
        migrations.AlterField(
            model_name='newshow',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 6, 1, 98869)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 6, 1, 100453)),
        ),
    ]
