# Generated by Django 4.1.4 on 2023-01-22 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_remove_reservation_date_alter_newshow_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newshow',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 12, 35, 268640)),
        ),
        migrations.AlterField(
            model_name='newshow',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 12, 35, 268640)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 23, 12, 35, 269774)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(default='untitled', max_length=100),
        ),
    ]
