# Generated by Django 4.1.4 on 2023-02-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_newshow_canceltime_alter_newshow_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelTime',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='newshow',
            name='cancelTime',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='newshow',
            name='endTime',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='newshow',
            name='startTime',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='startTime',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
        ),
    ]
